---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: sealed-secrets
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: sealed-secrets
      annotations:
        prometheus.io.scrape: "false"
    spec:
      serviceAccountName: sealed-secrets
      containers:
        - name: sealed-secrets
          command:
            - controller
          args:
            - "--key-name"
            - "sealed-secrets-key"
          image: quay.io/bitnami/sealed-secrets-controller:v0.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          resources:
            {}
